In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3871, 708, 9703, 9311],
 [3871, 708, 9703, 9307],
 [3871, 7741, 9703, 2624],
 [1183, 1869, 9189, 4006, 8646],
 [1183, 1869, 9189, 4006, 5023],
 [2950, 3871, 5999, 9703, 4026],
 [1597, 9775, 6900, 4006]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3871  708 9703 9311]
 [   0    0    0    0 3871  708 9703 9307]
 [   0    0    0    0 3871 7741 9703 2624]
 [   0    0    0 1183 1869 9189 4006 8646]
 [   0    0    0 1183 1869 9189 4006 5023]
 [   0    0    0 2950 3871 5999 9703 4026]
 [   0    0    0    0 1597 9775 6900 4006]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

d:\Gen AI Work\RNN Project\myenv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step


array([[[ 0.0268486 ,  0.0249042 ,  0.03590531, -0.00449953,
         -0.01287066, -0.03989595, -0.03083401,  0.0239092 ,
          0.01549549, -0.03165631],
        [ 0.0268486 ,  0.0249042 ,  0.03590531, -0.00449953,
         -0.01287066, -0.03989595, -0.03083401,  0.0239092 ,
          0.01549549, -0.03165631],
        [ 0.0268486 ,  0.0249042 ,  0.03590531, -0.00449953,
         -0.01287066, -0.03989595, -0.03083401,  0.0239092 ,
          0.01549549, -0.03165631],
        [ 0.0268486 ,  0.0249042 ,  0.03590531, -0.00449953,
         -0.01287066, -0.03989595, -0.03083401,  0.0239092 ,
          0.01549549, -0.03165631],
        [ 0.01341898,  0.00361926,  0.01347161,  0.0410669 ,
          0.02224726, -0.04144241,  0.04187905, -0.03429651,
         -0.01129226, -0.0302689 ],
        [-0.02794563, -0.03151643, -0.02798758, -0.03929013,
          0.04882008,  0.02141721,  0.04165808, -0.02703591,
         -0.03764058,  0.00990859],
        [ 0.01408884,  0.04967919,  0.02931033,  0.0

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 3871,  708, 9703, 9311], dtype=int32)

In [20]:
model.predict(embedded_docs[:1])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 255ms/step


array([[[ 0.0268486 ,  0.0249042 ,  0.03590531, -0.00449953,
         -0.01287066, -0.03989595, -0.03083401,  0.0239092 ,
          0.01549549, -0.03165631],
        [ 0.0268486 ,  0.0249042 ,  0.03590531, -0.00449953,
         -0.01287066, -0.03989595, -0.03083401,  0.0239092 ,
          0.01549549, -0.03165631],
        [ 0.0268486 ,  0.0249042 ,  0.03590531, -0.00449953,
         -0.01287066, -0.03989595, -0.03083401,  0.0239092 ,
          0.01549549, -0.03165631],
        [ 0.0268486 ,  0.0249042 ,  0.03590531, -0.00449953,
         -0.01287066, -0.03989595, -0.03083401,  0.0239092 ,
          0.01549549, -0.03165631],
        [ 0.01341898,  0.00361926,  0.01347161,  0.0410669 ,
          0.02224726, -0.04144241,  0.04187905, -0.03429651,
         -0.01129226, -0.0302689 ],
        [-0.02794563, -0.03151643, -0.02798758, -0.03929013,
          0.04882008,  0.02141721,  0.04165808, -0.02703591,
         -0.03764058,  0.00990859],
        [ 0.01408884,  0.04967919,  0.02931033,  0.0